# Version for this file.
version: 1

# The OS to compile for. `GOOS` env variable will be set to this value.
goos: linux darwin windows

# The architecture to compile for. `GOARCH` env variable will be set to this value.
goarch: 386 amd64 arm arm64

# Binary output name.
# {{ .Os }} will be replaced by goos field in the config file.
# {{ .Arch }} will be replaced by goarch field in the config file.
binary: binary-{{ .Os }}-{{ .Arch }}
